import json
import glob
import os
import re

def clean_text(text):
    if not text:
        return ""
    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    return text

def translate_patient_info(text):
    # Basic structural replacements
    replacements = {
        r'ICU住院编号': 'ICU Stay ID',
        r'对应患者编号': 'Patient ID',
        r'(\d+)岁男性': r'\1-year-old male',
        r'(\d+)岁女性': r'\1-year-old female',
        r'体重([\d.]+)kg': r'weight \1kg',
        r'【生命体征】': '\n[Vital Signs]',
        r'心率变化': 'Heart Rate',
        r'呼吸频率变化': 'Respiratory Rate',
        r'血氧饱和度变化': 'SpO2',
        r'平均动脉压变化': 'MAP',
        r'收缩压变化': 'SBP',
        r'舒张压变化': 'DBP',
        r'体温变化': 'Temperature',
        r'【SOFA评分相关特征】': '\n[SOFA Related Features]',
        r'氧合指数变化': 'PaO2/FiO2 Ratio',
        r'机械通气使用情况': 'Mechanical Ventilation',
        r'血小板计数变化': 'Platelets',
        r'总胆红素变化': 'Total Bilirubin',
        r'格拉斯哥昏迷评分变化': 'GCS Score',
        r'血清肌酐变化': 'Creatinine',
        r'尿量变化': 'Urine Output',
        r'血管活性药物使用剂量': 'Vasopressor Dose',
        r'【疾病评分】': '\n[Disease Scores]',
        r'SOFA总分变化': 'Total SOFA Score',
        r'SIRS评分变化': 'SIRS Score',
        r'（单位：次/分）': ' (Unit: bpm)',
        r'（单位：%）': ' (Unit: %)',
        r'（单位：mmHg）': ' (Unit: mmHg)',
        r'（单位：mg/dL）': ' (Unit: mg/dL)',
        r'（单位：×10³/μL）': ' (Unit: ×10³/μL)',
        r'（单位：分）': ' (Unit: points)',
        r'（单位：mL）': ' (Unit: mL)',
        r'（单位：℃）': ' (Unit: °C)',
        r'（单位：μg/kg/min）': ' (Unit: μg/kg/min)',
        r'（单位：）': ' (Unit: N/A)',
        r'监测持续时间为 0 小时（共 7 次测量，每4小时一次）：': 'Monitoring duration: 0 hours (7 measurements total, every 4 hours):',
    }
    
    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text)
        
    # Clean up any remaining Chinese punctuation
    text = text.replace('，', ', ').replace('。', '. ').replace('：', ': ')
    return text

def translate_intervention(text):
    # Phrase-based translation with padding spaces
    replacements = [
        (r'立即启动去甲肾上腺素输注', 'Immediate initiation of norepinephrine infusion'),
        (r'初始剂量为\s*([\d.]+)\s*μg·kg⁻¹·min⁻¹', r'initial dose of \1 μg/kg/min'),
        (r'维持剂量为\s*([\d.]+)\s*μg·kg⁻¹·min⁻¹', r'maintenance dose of \1 μg/kg/min'),
        (r'根据血压反应调整至最大\s*([\d.]+)\s*μg·kg⁻¹·min⁻¹', r'titrated to a maximum of \1 μg/kg/min based on blood pressure response'),
        (r'剂量调整间隔\s*(\d+)\s*小时', r'dose adjustment interval of \1 hours'),
        (r'密切监测血压和器官灌注', 'closely monitor blood pressure and organ perfusion'),
        (r'剂量呈递增趋势', 'showing an increasing dose trend'),
        (r'剂量呈递减趋势', 'showing a decreasing dose trend'),
        (r'提示血管反应性下降', 'indicating decreased vascular reactivity'),
        (r'提示血管反应性改善', 'indicating improved vascular reactivity'),
        (r'评估8小时内发生感染性休克的风险', 'assess the risk of developing septic shock within 8 hours'),
        (r'无血管活性药物干预措施', 'No vasopressor intervention initiated'),
        (r'建议密切监测血压和器官灌注', 'recommend close monitoring of blood pressure and organ perfusion'),
        (r'(\d+)小时', r'\1 hours'),
        (r'(\d+)分钟', r'\1 minutes'),
        (r'最大([\d.]+)μg·kg⁻¹·min⁻¹', r'maximum \1 μg/kg/min'),
        (r'未来8小时', 'Next 8 hours '),
        (r'患者当前SOFA评分(\d+)分', r"The patient's current SOFA score is \1 points "),
        (r'患者当前', "The patient is currently "),
        (r'提示多器官功能障碍', "indicating multiple organ dysfunction"),
        (r'多器官功能障碍', "multiple organ dysfunction"),
        (r'SIRS评分(\d+)分', r"SIRS score of \1 points "),
        (r'显示炎症反应强烈', "shows a strong inflammatory response"),
        (r'存在意识障碍和心率呼吸增快', "presence of consciousness disturbance and increased heart/respiratory rates"),
        (r'存在意识障碍', "presence of consciousness disturbance"),
        (r'心率呼吸增快', "increased heart and respiratory rates"),
        (r'符合脓毒症高风险状态', "consistent with a high-risk state for sepsis"),
        (r'干预措施为去甲肾上腺素初始剂量([\d.]+)μg·kg⁻¹·min⁻¹', r"The intervention involves an initial norepinephrine dose of \1 μg/kg/min"),
        (r'干预措施包括立即启动去甲肾上腺素输注', "Intervention measures include immediate initiation of norepinephrine infusion"),
        (r'目标血压维持', "to maintain target blood pressure"),
        (r'但剂量呈递增趋势（最大([\d.]+)μg·kg⁻¹·min⁻¹）', r"but the dose shows an increasing trend (maximum \1 μg/kg/min)"),
        (r'但剂量呈递增趋势', "but the dose shows an increasing trend"),
        (r'提示血管活性药物需求增加', "indicating increased vasopressor requirement"),
        (r'血管反应性下降', "decreased vascular reactivity"),
    ]
    
    for pattern, replacement in replacements.items() if isinstance(replacements, dict) else replacements:
        text = re.sub(pattern, replacement, text)
    
    # Clean up punctuation
    text = text.replace('，', ', ').replace('。', '. ').replace('、', ', ')
    return clean_text(text)

def translate_reasoning(text):
    # Short catch-all replacements (run last)
    short_replacements = [
        (r'提示', 'indicating '),
        (r'基于', 'Based on '),
        (r'干预措施', 'intervention measures '),
        (r'当前状态', 'current status '),
        (r'患者', 'The patient '),
        (r'当前', 'current '),
        (r'为', ' is '),
        (r'包括', ' include '),
        (r'由于', 'Due to '),
        (r'表明', 'indicates '),
        (r'预计', 'expected '),
        (r'需', ' need '),
        (r'处于', ' in '),
        (r'状态', ' state '),
        (r'（', ' ('),
        (r'）', ') '),
        (r'已属严重', 'is already severe'),
        (r'进而加重', 'consequently aggravating '),
    ]

    # Common medical phrases that appear in both sections
    common_replacements = [
        (r'立即启动去甲肾上腺素输注', 'Immediate initiation of norepinephrine infusion'),
        (r'初始剂量为?\s*([\d.]+)\s*μg·kg⁻¹·min⁻¹', r'initial dose of \1 μg/kg/min'),
        (r'初始剂量\s*([\d.]+)\s*μg·kg⁻¹·min⁻¹', r'initial dose of \1 μg/kg/min'),
        (r'维持剂量为?\s*([\d.]+)\s*μg·kg⁻¹·min⁻¹', r'maintenance dose of \1 μg/kg/min'),
        (r'根据血压反应调整至最大\s*([\d.]+)\s*μg·kg⁻¹·min⁻¹', r'titrated to a maximum of \1 μg/kg/min based on blood pressure response'),
        (r'根据血压反应调整至最大([\d.]+)μg·kg⁻¹·min⁻¹', r"titrated to a maximum of \1 μg/kg/min based on blood pressure response"),
        (r'剂量调整间隔\s*(\d+)\s*小时', r'dose adjustment interval of \1 hours'),
        (r'密切监测血压和器官灌注', 'closely monitor blood pressure and organ perfusion'),
        (r'剂量呈递增趋势', 'showing an increasing dose trend'),
        (r'剂量呈递减趋势', 'showing a decreasing dose trend'),
        (r'提示血管反应性下降', 'indicating decreased vascular reactivity'),
        (r'提示血管反应性改善', 'indicating improved vascular reactivity'),
        (r'评估8小时内发生感染性休克的风险', 'assess the risk of developing septic shock within 8 hours'),
        (r'无血管活性药物干预措施', 'No vasopressor intervention initiated'),
        (r'建议密切监测血压和器官灌注', 'recommend close monitoring of blood pressure and organ perfusion'),
        (r'最大([\d.]+)μg·kg⁻¹·min⁻¹', r'maximum \1 μg/kg/min'),
        (r'未来8小时', 'Next 8 hours '),
        (r'患者当前SOFA评分(\d+)分', r"The patient's current SOFA score is \1 points "),
        (r'患者当前', "The patient is currently "),
        (r'提示多器官功能障碍', "indicating multiple organ dysfunction"),
        (r'多器官功能障碍', "multiple organ dysfunction"),
        (r'SIRS评分(\d+)分', r"SIRS score of \1 points "),
        (r'显示炎症反应强烈', "shows a strong inflammatory response"),
        (r'存在意识障碍和心率呼吸增快', "presence of consciousness disturbance and increased heart/respiratory rates"),
        (r'存在意识障碍', "presence of consciousness disturbance"),
        (r'心率呼吸增快', "increased heart and respiratory rates"),
        (r'符合脓毒症高风险状态', "consistent with a high-risk state for sepsis"),
        (r'干预措施为去甲肾上腺素初始剂量([\d.]+)μg·kg⁻¹·min⁻¹', r"The intervention involves an initial norepinephrine dose of \1 μg/kg/min"),
        (r'干预措施包括立即启动去甲肾上腺素输注', "Intervention measures include immediate initiation of norepinephrine infusion"),
        (r'目标血压维持', "to maintain target blood pressure"),
        (r'但剂量呈递增趋势（最大([\d.]+)μg·kg⁻¹·min⁻¹）', r"but the dose shows an increasing trend (maximum \1 μg/kg/min)"),
        (r'但剂量呈递增趋势', "but the dose shows an increasing trend"),
        (r'提示血管活性药物需求增加', "indicating increased vasopressor requirement"),
        (r'血管反应性下降', "decreased vascular reactivity"),
    ]

    # Specific replacements
    replacements = [
        # Critical priority replacements (must run first)
        (r'not 来8 hours', 'Next 8 hours '),
        (r'high 于', 'higher than '),
        (r'high 度', 'highly '),
        (r'continue 性', 'persistent '),
        (r'stabilize性', 'stability'),
        (r'dependence性', 'dependence'),
        (r'improvetrend', 'improving trend'),
        (r'vasoactive drugdosage', 'vasoactive drug dosage'),
        (r'organ functionfurther', 'organ function further'),
        (r'未来\s*8\s*小时', 'Next 8 hours '),
        (r'高于', 'higher than '),
        (r'高度', 'highly '),
        (r'持续性', 'persistent '),
        (r'稳定性', 'stability'),
        (r'依赖性', 'dependence'),
        (r'启动', 'initiation of '),
        (r'输注', 'infusion'),
        (r'器官', 'organ '),
        (r'在\s*(\d+)\s*小时', r'Within \1 hours'),
        (r'在', 'At '), # Fallback
        (r'正常', 'normal '),
        (r'平均动脉压', 'MAP'),
        (r'去甲肾上腺素初始', 'initial norepinephrine '),
        (r'去甲肾上腺素', 'norepinephrine '),
        (r'高', 'high '),
        (r'提高', 'improve'),
        (r'血管活性药物', 'vasoactive drug'),
        (r'血管反应性', 'vascular reactivity'),
        (r'血管反应', 'vascular response'),
        (r'器官功能', 'organ function'),
        (r'凝血功能', 'coagulation function'),
        (r'肾功能', 'renal function'),
        (r'肝功能', 'liver function'),
        (r'神经系统功能', 'nervous system function'),
        (r'表现为', 'manifested as '),
        (r'收缩压', 'systolic blood pressure '),
        (r'心率', 'heart rate '),
        (r'体温', 'body temperature '),
        (r'意识', 'consciousness '),
        (r'允许值', 'allowed limit'),
        (r'灌注', 'perfusion'),
        (r'至', 'to '),
        (r'降低', 'decrease'),
        (r'降', 'decrease'),
        (r'上升', 'rise'),
        (r'上', 'increase'),
        (r'出现', 'presenting '),
        (r'出', 'presenting '),
        (r'较高', 'relatively high'),
        (r'较', 'relatively '),
        (r'can\s*can', 'may'),
        (r'异常', 'abnormal'),
        (r'反应调整至', 'adjusted based on response to '),
        (r'小时', ' hours'),
        (r'(\d+)分', r'\1 points'),
        (r'感染性休克', 'septic shock '),
        (r'脓毒症休克', 'septic shock '),
        (r'脓毒症管理指南', 'sepsis management guidelines'),
        (r'呈递增趋势', 'showing an increasing trend'),
        (r'呈递减趋势', 'showing a decreasing trend'),
        (r'往往预示', 'often indicates'),
        (r'高度警惕', 'high vigilance'),
        
        # New additions
        (r'高于', 'higher than '),
        (r'升高', 'increase '),
        (r'升', 'increase '),
        (r'危重', 'critical '),
        (r'支持', 'support '),
        (r'且', 'and '),
        (r'难以', 'difficult to '),
        (r'相关', 'related '),
        (r'特征', 'features '),
        (r'现', 'presenting '),
        (r'多系统', 'multiple system '),
        (r'最大', 'maximum '),
        (r'功能障碍', 'dysfunction '),
        (r'紧急', 'urgent '),
        (r'能', 'can '),
        (r'低', 'low '),
        (r'can\s*能', 'may '),
        (r'干预', 'intervention '),
        (r'measures', 'measures '),
        (r'高risk', 'high risk'),
        (r'further 展', 'further progression'),
        (r'展', 'progression'), # Fallback
        (r'循环', 'circulation '),
        (r'stabilize', 'stabilize '),
        (r'impact', 'impact '),
        (r'dependence', 'dependence '),
        (r'SOFA评分', 'SOFA score '),
        (r'improve', 'improve '),
        (r'trend', 'trend '),
        (r'time', 'time '),
        (r'recover', 'recover'),
        (r'analysis', 'analysis '),
        (r'shows', 'shows '),
        (r'all', 'all '),
        (r'under', 'under '),
        (r'failure', 'failure '),
        (r'probability', 'probability '),
        (r'presenting with', 'presenting with '),
        (r'challenge', 'challenge'),
        (r'deteriorate', 'deteriorate '),
        (r'risk', 'risk '),
        (r'indicators', 'indicators '),
        (r'may', 'may '),
        (r'GCS', 'GCS '),
        (r'mechanical ventilation', 'mechanical ventilation '),
        (r'continue', 'continue '),
        (r'effective', 'effective '),
        (r'but', 'but '),
        (r'temporarily', 'temporarily '),
        (r'increase', 'increase '),
        (r'indicating', 'indicating '),
        (r'due to', 'due to '),
        (r'hypoperfusion', 'hypoperfusion '),
        (r'drop', 'drop '),
        (r'from', 'from '),
        (r'to', 'to '),
        (r'count', 'count '),
        (r'rise', 'rise '),
        (r'absent to present', 'absent to present'),
        (r'Initial', 'Initial '),
        (r'Initiation', 'Initiation '),
        (r'infusion', 'infusion '),
        (r'maintain', 'maintain '),
        (r'dosage', 'dosage '),
        (r'adjustment', 'adjustment '),
        (r'interval', 'interval '),
        (r'closely', 'closely '),
        (r'Monitoring', 'Monitoring '),
        (r'blood pressure', 'blood pressure '),
        (r'organ perfusion', 'organ perfusion '),
        (r'showing', 'showing '),
        (r'decreasing', 'decreasing '),
        (r'vascular reactivity', 'vascular reactivity '),
        (r'Based on', 'Based on '),
        (r'current', 'current '),
        (r'status', 'status '),
        (r'and', 'and '),
        (r'expected', 'expected '),
        (r'Next 8 hours', 'Next 8 hours '),
        (r'gradually', 'gradually '),
        (r'Predicted', 'Predicted '),
        (r'is', 'is '),
        (r'However', 'However, '),
        (r'still', 'still '),
        (r'need', 'need '),
        (r'alert to', 'alert to '),
        (r'insufficient', 'insufficient '),
        (r'source control', 'source control '),
        (r'etc.', 'etc. '),
        
        # Late generic replacements
        # (r'高', 'high '), # Removed to prevent partial matches
        # (r'性', ' '), # Removed to prevent partial matches
        
        # Specific patterns from grep
        (r'炎症反应强烈', 'strong inflammatory response'),
        (r'高risk', 'high risk'),
        (r'干预measures', 'Intervention measures'),
        (r'target blood pressuremaintain', 'maintain target blood pressure'),
        (r'vasopressor requirementincrease', 'increased vasopressor requirement'),
        (r'vascular reactivitydrop', 'decreased vascular reactivity'),
        (r'continued increaseoften indicates', 'continued increase often indicates'),
        (r'septic shock further 展', 'further progression of septic shock'),
        (r'器官功能further deteriorate', 'further deterioration of organ function'),
        (r'vasopressor use increaseon', 'impact of increased vasopressor use on'),
        (r'sepsis on 多器官 continuous damage', 'continuous damage to multiple organs by sepsis'),
        (r'dependencevasopressor', 'dependence on vasopressor'),
        (r'maintain循环', 'maintain circulation'),
        (r'SOFA评分can 能drop', 'SOFA score may drop'),
        (r'Predicted is improvetrend', 'Predicted trend is improving'),
        (r'can 能', 'may '),
        (r'risk较高', 'high risk'),
        (r'循环failure', 'circulatory failure'),
        (r'nervous system functionimpaired', 'impaired nervous system function'),
        (r'难以maintain', 'difficult to maintain'),
        (r'病情deterioraterisk', 'risk of condition deterioration'),
        (r'SOFA评分相关indicators', 'SOFA score related indicators'),
        (r'SOFA评分相关特征', 'SOFA score related features'),
        (r'improvetrend', 'improving trend'),
        (r'部分indicators', 'some indicators'),
        (r'timerecover', 'time to recover'),
        (r'Although However', 'Although'),
        (r'blood pressurecontrolcan 能still not stabilize', 'blood pressure control may still not stabilize'),
        (r'organ perfusionrisk高', 'high risk of organ perfusion issues'),
        (r'continue deteriorate', 'continue to deteriorate'),
        (r'高dosage', 'high dosage'),
        (r'Total SOFA score8分', 'Total SOFA score 8 points'),
        (r'vasopressor dependence性', 'vasopressor dependence'),
        (r'key 干预measures', 'key intervention measures'),
        (r'器官功能failure', 'organ failure'),
        (r'vascular reactivitycurrently improve', 'vascular reactivity is currently improving'),
        (r'decreasingusually', 'decreasing usually'),
        (r'continue drop', 'continue to drop'),
        (r'infectionnot fully controlled', 'infection not fully controlled'),
        (r'relapserisk', 'relapse risk'),
        (r'SOFA评分相关indicatorsin', 'Among SOFA score related indicators'),
        (r'病情changes', 'condition changes'),
        (r'presenting with 感染not control', 'presenting with uncontrolled infection'),
        (r'多系统failure', 'multiple system failure'),
        (r'尤其是septic shock', 'especially septic shock'),
        (r'outcome is deteriorating', 'outcome is deteriorating'),
        (r'低blood pressure', 'low blood pressure'),
        (r'hypothermia', 'hypothermia'),
        (r'意识 state 改变', 'altered consciousness state'),
        (r'active 干预can slow down deterioraterate', 'active intervention can slow down deterioration rate'),
        (r'not use vasopressor', 'do not use vasopressor'),
        (r'shock further 展risk', 'risk of further shock progression'),
        (r'SOFA评分trendanalysisshows', 'SOFA score trend analysis shows'),
        (r'urine outputdecreaseetc.', 'urine output decrease, etc.'),
        (r'indicatorsall point to', 'indicators all point to'),
        (r'No 干预measuresunder', 'Under no intervention measures'),
        (r'failureprobability', 'failure probability'),
        (r'blood pressurecontrolpresenting with challenge', 'blood pressure control presenting with challenges'),
        (r'blood pressurestabilize性', 'blood pressure stability'),
        (r'septic shock deterioraterisk', 'septic shock deterioration risk'),
        (r'indicatorscan 能', 'indicators may'),
        (r'vasopressor dosage can 能increase', 'vasopressor dosage may increase'),
        (r'GCScan 能drop', 'GCS may drop'),
        (r'mechanical ventilationcan 能continue', 'mechanical ventilation may continue'),
        (r'多器官功能failure', 'multiple organ failure'),
        (r'riskstillpresenting with', 'risk still presenting with'),
        (r'normal heart ratebut', 'normal heart rate but'),
        (r'active vasopressor 干预can 能temporarily stabilize病情', 'active vasopressor intervention may temporarily stabilize the condition'),
        (r'increaseindicating', 'increase indicating'),
        (r'analysis SOFA相关特征', 'Analyze SOFA related features'),
        (r'can 能due to', 'may due to'),
        (r'多器官', 'multiple organs'),
        (r'病情', 'condition'),
        (r'部分', 'some '),
        (r'尤其是', 'especially '),
        (r'符合', 'consistent with '),
        (r'提示', 'indicating '),
        (r'指标', 'indicators'),
        (r'关键', 'key '),
        (r'逐步', 'gradually '),
        (r'逐渐', 'gradually '),
        (r'出现', 'appear '),
        (r'因', 'due to '),
        (r'这', 'this '),
        (r'通常', 'usually '),
        (r'减轻', 'alleviate'),
        (r'虽', 'Although '),
        (r'神经系统功能', 'nervous system function'),
        (r'stabilize性', 'stability'),
        (r'dependence性', 'dependence'),
        (r'限制', 'limit'),
        (r'风险', 'risk'),
        (r'衰竭', 'failure'),
        (r'早期', 'early '),
        (r'阶段', 'stage'),
        (r'继续', 'continue '),
        (r'但', 'but '),
        (r'以及', 'and '),
        (r'措施', 'measures'),
        (r'中', 'in '),
        (r'需', 'need '),
        (r'分析', 'analysis'),
        (r'显示', 'shows'),
        (r'可', 'can '),
        (r'减缓', 'slow down '),
        (r'速度', 'rate'),
        (r'复发', 'relapse'),
        
        # General terms
        (r'感染性', 'septic '),
        (r'脓毒症', 'sepsis '),
        (r'管理指南', 'management guidelines'),
        (r'高风险', 'high risk'),
        (r'早期阶段', 'early stage'),
        (r'可能', 'may '),
        (r'进入', 'enter '),
        (r'更', 'more '),
        (r'呈', 'showing '),
        (r'递增', 'increasing'),
        (r'递减', 'decreasing'),
        (r'往往', 'often '),
        (r'预示着', 'indicates '),
        (r'预示', 'indicates '),
        (r'缓解', 'remission'),
        (r'受损', 'impaired'),
        (r'属', 'is '),
        (r'缺乏', 'Lacking '),
        (r'将', 'will '),
        (r'等', 'etc.'),
        (r'显著', 'significantly '),
        (r'升高', 'increase'),
        (r'降低', 'decrease'),
        (r'维持', 'maintain'),
        (r'调整间隔', 'adjustment interval'),
        (r'目标', 'target '),
        (r'依赖', 'dependence'),
        (r'积极', 'active '),
        (r'治疗', 'treatment '),
        (r'手段', 'measures'),
        (r'高度', 'highly '),
        (r'次/分', ' bpm'),

        # Fixes for order issues and missing terms
        (r'未来8小时', 'Next 8 hours '), # Ensure this runs before '未'
        (r'未及时', 'failure to timely '),
        (r'未采取', 'failure to take '),
        (r'未', 'not '), # Fallback for '未' if not caught above
        
        (r'表现为', 'manifested as '),
        (r'表现', 'manifestation '),
        
        (r'持续低血压', 'persistent hypotension'),
        (r'持续性低血压', 'persistent hypotension'),
        (r'显著降低', 'significantly reduced'),
        (r'临床经验', 'clinical experience'),
        (r'持续增加', 'continued increase'),
        (r'考虑', 'consider '),
        (r'立即', 'Immediate '),
        (r'循环稳定性', 'circulatory stability'),
        (r'将逐步改善', 'will gradually improve'),
        (r'感染源控制不足', 'insufficient source control'),
        (r'及时', 'timely'),
        (r'可能导致', 'may lead to '),
        (r'采取积极', 'take active '),
        (r'进一步下降', 'further drop'),
        (r'难以维持', 'difficult to maintain'),
        (r'不足', 'insufficient'),
        (r'监测建议', 'Monitoring recommendations'),
        (r'部分指标', 'some indicators'),
        (r'如', 'such as '),
        (r'等指标', 'indicators such as'),
        (r'指向', 'point to '),
        (r'有效', 'effective'),
        (r'计数', 'count'),
        (r'总', 'Total '),
        (r'血清', 'Serum '),
        (r'无到有', 'absent to present'),
        (r'仍', 'still '),
        (r'需', 'need '),
        (r'或者', 'or '),
        (r'以及', 'and '),
        (r'导致', 'leading to '),
        (r'概率', 'probability '),
        (r'增加', 'increase'),
        (r'减少', 'decrease'),
        (r'下降', 'drop'),
        (r'上升', 'rise'),
        (r'改善', 'improve'),
        (r'恶化', 'deteriorate'),
        (r'稳定', 'stabilize'),
        (r'波动', 'fluctuation'),
        (r'恢复', 'recover'),
        (r'完全控制', 'fully controlled'),
        (r'缓解', 'remission'),
        (r'复发', 'relapse'),
        
        # Third batch of specific fixes
        (r'血管活性药物', 'vasopressor '),
        (r'血管反应性', 'vascular reactivity'),
        (r'循环稳定性', 'circulatory stability'),
        (r'紧急干预', 'urgent intervention'),
        (r'密切', 'closely '),
        (r'建议', 'recommend '),
        (r'若', 'if '),
        (r'内', ' '), # Remove '内' as it often appears after 'Next 8 hours'
        (r'明显', 'significantly '),
        (r'进一步', 'further '),
        (r'使用', 'use '),
        (r'实施', 'implement '),
        (r'循环衰竭', 'circulatory failure'),
        (r'凝血功能', 'coagulation function'),
        (r'有望', 'expected to '),
        (r'正在', 'currently '),
        (r'均', 'all '),
        (r'高于', 'higher than '),
        (r'稳定性', 'stability'),
        (r'评估', 'assess '),
        (r'低灌注', 'hypoperfusion'),
        (r'而', ' '),
        (r'Total 结', 'Summary'),
        (r'SOFATotal 分', 'Total SOFA score'),
        (r'still 然', 'still'),
        (r'need 求', 'requirement'),
        (r'need 要', 'need'),
        (r'持续损害', 'continuous damage'),
        (r'影响', 'impact'),
        (r'对', 'on '),
        (r'的', ' '), # Generic 'of'/'s' removal if loose
        (r'不', 'not '),
        (r'控制', 'control'),
        (r'时间', 'time'),
        (r'持续', 'continue '),
        
        # Final cleanup batch
        (r'平均动脉压', 'MAP'),
        (r'剂量', 'dosage '),
        (r'警惕', 'alert to '),
        (r'然', 'However, '),
        (r'进', 'further '),
        (r'加重', 'aggravate '),
        (r'无', 'No '),
        (r'仅', 'Only '),
        (r'休克', 'shock '),
        (r'严重', 'severe '),
        (r'提升', 'improvement '),
        (r'在8小时', 'Within 8 hours '),
        (r'动态调整', 'dynamically adjust '),
        (r'随', 'with '),
        (r'变化', 'changes '),
        (r'会', 'will '),
        (r'下', 'under '),
        (r'进展', 'progression '),
        (r'挑战', 'challenge '),
        (r'最大允许值', 'maximum allowed value'),
        (r'或', 'or '),
        (r'以防止', 'to prevent '),
        (r'暂时', 'temporarily '),
        (r'动脉压', 'Arterial Pressure'),
        (r'平', 'Mean'),
        
        # New additions for remaining Chinese text
        (r'密切Monitoring', 'closely monitor '),
        (r'干预措施', 'intervention measures '),
        (r'仅It is recommended to', 'It is only recommended to '),
        (r'仅建议密切监测', 'Only close monitoring is recommended'),
        (r'建议closely monitor', 'recommend closely monitoring'), 
        (r'且无干预', 'and no intervention'),
        (r'未采取积极干预', 'no active intervention taken'),
        (r'警惕感染持续', 'alert to persistent infection'),
        (r'根据', 'According to '),
        (r'SOFA评分相关特征将呈现', 'SOFA score related features will show '),
        (r'呈递减趋势', 'showing a decreasing trend'),
        (r'血管反应性正在改善', 'vascular reactivity is improving'),
        (r'血管活性药物剂量递减通常预示着循环稳定性的提升', 'Decreasing vasopressor dosage usually indicates improved circulatory stability'),
        (r'在8小时内', 'Within 8 hours'),
        (r'若血管活性药物剂量持续下降', 'if vasopressor dosage continues to decrease'),
        (r'可能预示着septic shock的缓解', 'may indicate remission of septic shock'),
        (r'导致的复发风险', 'risk of relapse caused by'),
        (r'SOFA评分相关指标中', 'Among SOFA score related indicators'),
        (r'氧合指数', 'oxygenation index'),
        (r'血小板', 'platelets'),
        (r'胆红素', 'bilirubin'),
        (r'血管活性药物剂量', 'vasopressor dosage'),
        (r'格拉斯哥昏迷评分', 'Glasgow Coma Scale score'),
        (r'肌酐', 'creatinine'),
        (r'尿量', 'urine output'),
        (r'机械通气', 'mechanical ventilation'),
        (r'均会随病情变化而动态调整', 'will dynamically adjust with condition changes'),
        (r'趋势', 'trend'),
        (r'病情将逐步改善', 'condition will gradually improve'),
        (r'仍presenting with', 'still presenting with'),
        (r'感染未控制', 'uncontrolled infection'),
        (r'器官功能恶化等风险', 'risks such as organ function deterioration'),
        (r'凝血系统', 'coagulation system'),
        (r'肾功能', 'renal function'),
        (r'肝功能', 'liver function'),
        (r'炎症反应活跃', 'active inflammatory response'),
        (r'无血管活性药物支持', 'no vasopressor support'),
        (r'出现多系统衰竭', 'multiple system failure appearing'),
        (r'病情危重', 'critical condition'),
        (r'治疗手段', 'treatment methods'),
        (r'时干预的严重脓毒症The patient', 'timely intervention for severe sepsis patients'),
        (r'尤其是septic shock风险高', 'especially high risk of septic shock'),
        (r'结果', 'outcome'),
        (r'低体温', 'hypothermia'),
        (r'意识 state 改变', 'altered consciousness state'),
        (r'SOFA评分显著升高', 'SOFA score significantly increased'),
        (r'可能因血管活性药物剂量增加而出现血压波动', 'may experience blood pressure fluctuations due to increased vasopressor dosage'),
        (r'积极干预可减缓恶化速度', 'active intervention can slow down the deterioration rate'),
        (r'总结', 'summary'),
        (r'血小板显著下降', 'significant decrease in platelets'),
        (r'严重high risk', 'severe high risk'),
        (r'中未使用血管活性药物', 'no vasopressor used in'),
        (r'导致multiple organ dysfunction', 'leading to multiple organ dysfunction'),
        (r'SOFA评分趋势分析显示', 'SOFA score trend analysis shows'),
        (r'血小板下降', 'platelet decrease'),
        (r'氧合指数可能恶化', 'oxygenation index may deteriorate'),
        (r'尿量减少等指标均指向病情恶化', 'indicators such as decreased urine output all point to condition deterioration'),
        (r'无干预 measures下', 'Under no intervention measures'),
        (r'概率增加', 'probability increases'),
        (r'启动去甲肾上腺素输注', 'Initiation of norepinephrine infusion'),
        (r'初始剂量', 'initial dose'),
        (r'最大剂量限制', 'maximum dose limit'),
        (r'这indicates', 'this indicates'),
        (r'血压控制presenting with 挑战', 'blood pressure control presenting with challenges'),
        (r'初始剂量高于最大允许值', 'Initial dose higher than maximum allowed value'),
        (r'可能影响血压稳定性', 'may affect blood pressure stability'),
        (r'评估septic shock恶化风险', 'assess the risk of septic shock deterioration'),
        (r'等指标可能进一步恶化', 'and other indicators may further deteriorate'),
        (r'可能增加', 'may increase'),
        (r'GCS可能下降', 'GCS may decrease'),
        (r'可能恶化', 'may deteriorate'),
        (r'可能持续或增加', 'may continue or increase'),
        (r'严重consciousness disturbance', 'severe consciousness disturbance'),
        (r'多器官功能衰竭', 'multiple organ failure'),
        (r'血压 and 器官灌注将逐步改善', 'blood pressure and organ perfusion will gradually improve'),
        (r'多器官功能衰竭仍', 'multiple organ failure still'),
        (r'以防止恶化', 'to prevent deterioration'),
        (r'心率正常', 'normal heart rate'),
        (r'血压显著降低', 'significant blood pressure drop'),
        (r'SOFA评分持续上升', 'SOFA score continuously rising'),
        (r'警惕septic shock的进展', 'alert to the progression of septic shock'),
        (r'血压可能进一步下降', 'blood pressure may further drop'),
        (r'积极的血管活性药物干预可能暂时稳定病情', 'active vasopressor intervention may temporarily stabilize the condition'),
        (r'然而', 'However'),
        (r'高度警惕', 'high vigilance'),
        (r'分析SOFA相关特征', 'Analyze SOFA related features'),
        (r'可能因低灌注而下降', 'may decrease due to hypoperfusion'),
        (r'从', 'from '),
        (r'降至', 'drop to '),
        (r'可能继续减少', 'may continue to decrease'),
        (r'总胆红素可能上升', 'Total bilirubin may rise'),
        (r'升至', 'rise to '),
        (r'血管活性药物剂量递增', 'Vasopressor dosage increasing'),
        (r'可能从无到有', 'may go from none to present'),
        (r'血压', 'blood pressure'),
        (r'器官灌注', 'organ perfusion'),
        (r'未', 'failure to '),
        (r'平均动脉压', 'MAP'),
        
        (r'患者当前SOFA评分(\d+)分', r"The patient's current SOFA score is \1 points "),
        (r'患者当前', "The patient is currently "),
        (r'建议', "It is recommended to "),
        (r'提示多器官功能障碍', "indicating multiple organ dysfunction"),
        (r'多器官功能障碍', "multiple organ dysfunction"),
        (r'SIRS评分(\d+)分', r"SIRS score of \1 points "),
        (r'显示炎症反应强烈', "shows a strong inflammatory response"),
        (r'存在意识障碍和心率呼吸增快', "presence of consciousness disturbance and increased heart/respiratory rates"),
        (r'存在意识障碍', "presence of consciousness disturbance"),
        (r'心率呼吸增快', "increased heart and respiratory rates"),
        (r'符合脓毒症高风险状态', "consistent with a high-risk state for sepsis"),
        (r'干预措施为去甲肾上腺素初始剂量([\d.]+)μg·kg⁻¹·min⁻¹', r"The intervention involves an initial norepinephrine dose of \1 μg/kg/min"),
        (r'干预措施包括立即启动去甲肾上腺素输注', "Intervention measures include immediate initiation of norepinephrine infusion"),
        (r'目标血压维持', "to maintain target blood pressure"),
        (r'但剂量呈递增趋势（最大([\d.]+)μg·kg⁻¹·min⁻¹）', r"but the dose shows an increasing trend (maximum \1 μg/kg/min)"),
        (r'但剂量呈递增趋势', "but the dose shows an increasing trend"),
        (r'提示血管活性药物需求增加', "indicating increased vasopressor requirement"),
        (r'血管反应性下降', "decreased vascular reactivity"),
        (r'根据临床经验', "Based on clinical experience"),
        (r'血管活性药物剂量持续增加', "continued increase in vasopressor dosage"),
        (r'往往预示脓毒症休克进展', "often predicts progression to septic shock"),
        (r'需警惕器官功能进一步恶化', "alertness for further organ function deterioration is required"),
        (r'未来8小时预测需考虑', "Future 8-hour prediction needs to consider"),
        (r'血管活性药物使用增加对循环稳定的影响', "the impact of increased vasopressor use on circulatory stability"),
        (r'以及脓毒症对多器官的持续损害', "and the continuous damage of sepsis to multiple organs"),
        (r'患者当前处于感染性休克状态', "The patient is currently in a state of septic shock"),
        (r'表现为持续低血压（收缩压([\d.]+) mmHg）', r"manifested as persistent hypotension (SBP \1 mmHg)"),
        (r'表现为持续低血压', "manifested as persistent hypotension"),
        (r'表现为持续性低血压（收缩压(\d+)-(\d+) mmHg）', r"manifested as persistent hypotension (SBP \1-\2 mmHg)"),
        (r'表现为持续性低血压', "manifested as persistent hypotension"),
        (r'心动过速（心率([\d.]+) bpm）', r"tachycardia (HR \1 bpm)"),
        (r'严重心动过速（心率(\d+)-(\d+)次/分）', r"severe tachycardia (HR \1-\2 bpm)"),
        (r'心率([\d.]+)次/分', r"heart rate \1 bpm"),
        (r'收缩压([\d.]+) mm Hg', r"SBP \1 mmHg"),
        (r'平均动脉压([\d.]+) mm Hg', r"MAP \1 mmHg"),
        (r'GCS (\d+)分', r"GCS score of \1 points"),
        (r'及依赖血管活性药物（([\d.]+) μg/kg/min）', r"and dependence on vasopressors (\1 μg/kg/min)"),
        (r'需血管活性药物支持（([\d.-]+) μg/kg/min）', r"requiring vasopressor support (\1 μg/kg/min)"),
        (r'无血管活性药物干预', "no vasopressor intervention"),
        (r'缺乏关键', "lacking key "),
        (r'如血管活性药物', "such as vasopressors"),
        (r'可能导致病情进一步恶化', "may lead to further deterioration of the condition"),
        (r'警惕器官功能衰竭风险', "be alert to the risk of organ failure"),
        (r'预测', "Predicted "),
        (r'若不采取积极干预', "if active intervention is not taken"),
        (r'可能进入更严重的休克', "may enter a more severe shock"),
        (r'已', "already "),
        (r'感染性休克早期阶段', "early stage of septic shock"),
         (r'感染性休克高风险', "high risk of septic shock"),
         (r'感染性休克', "septic shock"),
         (r'脓毒症休克', "septic shock"),
         (r'改善趋势', "an improving trend"),
         (r'进一步加重', "further aggravating "),
         (r'存在低血压', "presenting with hypotension"),
         (r'存在', "presenting with "),
         (r'措施', " measures"),
         (r'属严重', "is severe"),
         (r'监测建议', "Monitoring recommendations"),
         (r'监测', "Monitoring "),
         (r'风险较高', "high risk"),
         (r'可能继续恶化', "may continue to deteriorate"),
         (r'收缩压\s*([\d.]+)\s*mm\s*Hg', r"SBP \1 mmHg"),
         (r'维持循环', "to maintain circulation"),
        (r'SOFA评分(\d+)分', r"SOFA score of \1 points "),
        (r'SOFA总分(\d+)分', r"Total SOFA score of \1 points "),
        (r'需紧急干预', "requires urgent intervention"),
        (r'立即启动去甲肾上腺素输注', "Immediate initiation of norepinephrine infusion"),
        (r'维持剂量为([\d.]+)μg·kg⁻¹·min⁻¹', r"maintenance dose of \1 μg/kg/min"),
        (r'初始剂量为([\d.]+)μg·kg⁻¹·min⁻¹', r"initial dose of \1 μg/kg/min"),
        (r'剂量调整间隔(\d+)小时', r"dose adjustment interval of \1 hours"),
        (r'密切监测血压和器官灌注', "closely monitor blood pressure and organ perfusion"),
        (r'剂量呈递减趋势', "the dose shows a decreasing trend"),
        (r'提示血管反应性改善', "indicating improved vascular reactivity"),
        (r'基于当前干预措施', "Based on current intervention measures"),
        (r'预计未来8小时血压和循环稳定性将逐步改善', "blood pressure and circulatory stability are expected to gradually improve over the next 8 hours"),
        (r'SOFA评分可能下降', "SOFA score may decrease"),
        (r'预测为改善趋势', "predicted as an improving trend"),
        (r'然而，仍需警惕', "However, vigilance is still needed for"),
        (r'感染源控制不足', "insufficient source control"),
        (r'器官功能进一步恶化等风险', "and risks of further organ function deterioration"),
        (r'氧合指数显著降低（初始([\d.]+) mmHg）', r"significantly reduced oxygenation index (initial \1 mmHg)"),
        (r'由于血管活性药物剂量呈递增趋势', "Due to the increasing trend of vasopressor dosage"),
        (r'可能预示病情恶化', "may predict condition deterioration"),
        (r'氧合指数低（([\d.]+) mmHg）', r"low oxygenation index (\1 mmHg)"),
        (r'和SOFA评分高（(\d+)分）', r"and high SOFA score (\1 points)"),
        (r'表明患者处于危重状态', "indicates the patient is in a critical condition"),
        (r'需持续监测和干预', "requiring continuous monitoring and intervention"),
        (r'未来8小时内', "Within the next 8 hours "),
        (r'若血管活性药物剂量增加', "if vasopressor dosage increases"),
        (r'但血压未明显改善', "but blood pressure does not significantly improve"),
        (r'可能导致器官灌注不足', "it may lead to insufficient organ perfusion"),
        (r'进一步加重多器官功能障碍', "further aggravating multiple organ dysfunction"),
        (r'患者当前存在低血压', "The patient currently presents with hypotension"),
        (r'血小板减少', "thrombocytopenia"),
        (r'提示感染性休克高风险', "indicating a high risk of septic shock"),
        (r'仅建议密切监测', "only close monitoring is recommended"),
        (r'未采取积极治疗手段', "with no active treatment measures taken"),
        (r'根据脓毒症管理指南', "According to sepsis management guidelines"),
        (r'未及时使用血管活性药物', "failure to use vasopressors in a timely manner"),
        (r'可能导致血压进一步下降', "may lead to a further drop in blood pressure"),
        (r'器官灌注不足', "insufficient organ perfusion"),
        (r'进而加重多器官功能障碍', "consequently aggravating multiple organ dysfunction"),
        (r'SOFA评分12分已属严重', "A SOFA score of 12 is severe"),
        (r'且无干预措施', "and with no intervention measures"),
        (r'未来8小时风险较高', "the risk is high for the next 8 hours"),
        (r'患者当前处于脓毒症休克状态', "The patient is currently in a state of septic shock"),
        (r'表现为循环衰竭', "manifested as circulatory failure"),
        (r'神经系统功能受损', "nervous system impairment"),
        (r'及多器官功能障碍', "and multiple organ dysfunction"),
        (r'但未实施血管活性药物干预', "but no vasopressor intervention has been implemented"),
        (r'缺乏血管活性药物支持将导致血压难以维持', "Lack of vasopressor support will make it difficult to maintain blood pressure"),
        (r'监测建议表明当前风险较高', "Monitoring recommendations indicate a high current risk"),
        (r'且未采取积极干预措施', "and no active intervention measures have been taken"),
        (r'会显著增加病情恶化风险', "will significantly increase the risk of deterioration"),
        (r'SOFA评分相关指标（如氧合指数、血小板、胆红素等）', "SOFA-related indicators (such as oxygenation index, platelets, bilirubin, etc.)"),
        (r'预计将持续恶化', "are expected to continue deteriorating"),
        (r'提示未来8小时病情可能进一步加重', "suggesting the condition may worsen further in the next 8 hours"),
        (r'意识障碍', "consciousness disturbance"),
        (r'凝血功能异常', "coagulation abnormalities"),
        (r'及需要血管活性药物支持', " and requiring vasopressor support"),
        (r'意识障碍可能减轻', "consciousness disturbance may alleviate"),
        (r'但需警惕感染持续存在', "but vigilance is needed for persistent infection"),
        (r'器官功能进一步受损的风险', "and the risk of further organ function damage"),
        (r'SOFA评分相关特征将呈现改善趋势', "SOFA-related features are expected to show an improving trend"),
        (r'但部分指标如凝血功能和尿量可能仍需时间恢复', "but some indicators like coagulation and urine output may still take time to recover"),
        (r'表现为低血压', "manifested as hypotension"),
        (r'SOFA评分升高', "increased SOFA score"),
        (r'虽然血管活性药物剂量增加', "Although vasopressor dosage is increasing"),
        (r'但血压控制可能仍不稳定', "blood pressure control may still be unstable"),
        (r'器官灌注风险高', "risk of organ perfusion issues is high"),
        (r'需密切监测', "Close monitoring is required"),
        (r'预测未来8小时可能继续恶化', "predicting possible continued deterioration in the next 8 hours"),
        (r'持续性低血压', "persistent hypotension"),
        (r'高剂量血管活性药物依赖（([\d.]+)μg/kg/min）', r"dependence on high-dose vasopressors (\1 μg/kg/min)"),
        (r'器官功能有望改善', "organ function is expected to improve"),
        (r'但需警惕感染未完全控制', "but vigilance is needed for infection not being fully controlled"),
        (r'及器官功能进一步恶化的风险', " and the risk of further organ function deterioration"),
        (r'需血管活性药物维持血压', "requiring vasopressors to maintain blood pressure"),
        (r'基于此', "Based on this"),
        (r'预计未来8小时血压将逐步稳定', "blood pressure is expected to stabilize gradually over the next 8 hours"),
        (r'器官灌注改善', "organ perfusion to improve"),
        (r'血管活性药物依赖性', "vasopressor dependence"),
        (r'及器官功能进一步恶化风险', "and risk of further organ function deterioration"),
        (r'根据血压反应调整至最大([\d.]+)μg·kg⁻¹·min⁻¹', r"titrated to a maximum of \1 μg/kg/min based on blood pressure response"),
        (r'患者当前处于感染性休克高风险状态', "The patient is currently at high risk of septic shock"),
        (r'根据当前状态和干预措施', "Based on the current status and intervention measures"),
        (r'患者循环功能将逐步改善', "the patient's circulatory function will gradually improve"),
        (r'可能减轻', "may alleviate"),
        (r'和', " and "),
        (r'及', " and "),
        (r'但', " but "),
        (r'心动过速', "tachycardia"),
        (r'预计Within', "expected within"),
        (r'血管活性药物剂量将逐渐减少', "vasopressor dosage will gradually decrease"),
        (r'血压将逐步稳定', "blood pressure will gradually stabilize"),
        (r'（单位：', ' (Unit: '),
        (r'）', ')'),
        (r'、', ', '),
        (r'，', ', '),
        (r'。', '. '),
    ]

    # Apply replacements in order: common -> specific -> short
    for pattern, replacement in common_replacements + replacements + short_replacements:
        text = re.sub(pattern, replacement, text)
        
    # Clean up multiple spaces and ensure space after comma/period
    text = re.sub(r'\s+', ' ', text)
    text = text.replace(' ,', ',').replace(' .', '.')
    text = re.sub(r',(?! )', ', ', text)
    text = re.sub(r'\.(?![\d ])', '. ', text)
    text = re.sub(r'\.(?=\s)', '.', text) # If already followed by space, leave it (or ensure single space)
    # Actually, simpler: replace dot not followed by digit with dot+space, then collapse spaces
    text = re.sub(r'\.(?!\d)', '. ', text)
    text = re.sub(r',(?![\d])', ', ', text) # Avoid breaking 1,000 if it exists, though unlikely
    
    # Add space between lowercase and uppercase letters (e.g., "dosageOften")
    text = re.sub(r'([a-z])([A-Z])', r'\1 \2', text)
    
    # Add space between letter and opening parenthesis
    text = re.sub(r'([a-zA-Z])\(', r'\1 (', text)
    
    # Add space between closing parenthesis and letter
    text = re.sub(r'\)([a-zA-Z])', r') \1', text)
    
    # Add space between digit and letter (e.g., "75bpm")
    text = re.sub(r'(\d)([a-zA-Z])', r'\1 \2', text)

    text = re.sub(r'\s+', ' ', text)
    
    return clean_text(text)

def main():
    output_dir = "/data/wzx/output/best_result"
    json_files = sorted(glob.glob(os.path.join(output_dir, "result_*.json")))
    
    latex_output = []
    latex_output.append("% Generated Summary of Best Results (English Translation)")
    latex_output.append("\\documentclass{article}")
    latex_output.append("\\usepackage{listings}")
    latex_output.append("\\usepackage{caption}")
    latex_output.append("\\usepackage[utf8]{inputenc}")
    latex_output.append("\\begin{document}")
    latex_output.append("")
    
    for json_file in json_files:
        try:
            with open(json_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            patient_id = os.path.basename(json_file).replace("result_", "").replace(".json", "")
            
            input_desc = translate_patient_info(data.get('input_description', ''))
            intervention = translate_intervention(data.get('intervention', ''))
            
            reasoning = data.get('reasoning', '')
            if not reasoning:
                 if 'prediction_data' in data and 'prediction' in data['prediction_data']:
                        reasoning = data['prediction_data']['prediction'].get('intervention_analysis', {}).get('reasoning', '')
            
            reasoning = translate_reasoning(reasoning)
            risk = data.get('risk_level', '')
            
            latex_block = f"\\begin{{lstlisting}}[caption={{Result for Patient {patient_id}}}, label={{lst:{patient_id}}}]\n"
            latex_block += "Patient Information:\n"
            latex_block += input_desc + "\n\n"
            latex_block += "Intervention Plan:\n"
            latex_block += intervention + "\n\n"
            latex_block += "Reasoning:\n"
            latex_block += reasoning + "\n\n"
            latex_block += "Risk Level: " + risk + "\n"
            latex_block += "\\end{lstlisting}\n"
            
            latex_output.append(latex_block)
            
        except Exception as e:
            print(f"Error processing {json_file}: {e}")
            
    latex_output.append("\\end{document}")
    
    with open("/data/wzx/best_result_summary.tex", "w", encoding="utf-8") as f:
        f.write("\n".join(latex_output))

if __name__ == "__main__":
    main()
